{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e2749a83",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-25T15:02:38.621686Z",
     "iopub.status.busy": "2026-03-25T15:02:38.619490Z",
     "iopub.status.idle": "2026-03-25T15:02:39.540335Z",
     "shell.execute_reply": "2026-03-25T15:02:39.537930Z"
    },
    "papermill": {
     "duration": 0.929473,
     "end_time": "2026-03-25T15:02:39.543006",
     "exception": false,
     "start_time": "2026-03-25T15:02:38.613533",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train: 1120 filas | Test: 280 filas\n",
      "Metodo: VR-ball  alpha=0.5  eps-pctile=20%  expand x1.5\n",
      "\n",
      "  [learning]\n",
      "    epsilon=1.7970  |  vecinos promedio: 49.0\n",
      "    -> 60 predicciones\n",
      "\n",
      "  [metacognition]\n",
      "    epsilon=0.3103  |  vecinos promedio: 46.7\n",
      "    -> 60 predicciones\n",
      "\n",
      "  [attention]\n",
      "    epsilon=0.6136  |  vecinos promedio: 36.8\n",
      "    -> 40 predicciones\n",
      "\n",
      "  [executive_functions]\n",
      "    epsilon=1.3419  |  vecinos promedio: 48.8\n",
      "    -> 60 predicciones\n",
      "\n",
      "  [social_cognition]\n",
      "    epsilon=0.9595  |  vecinos promedio: 51.5\n",
      "    -> 60 predicciones\n",
      "\n",
      "Submission -> /kaggle/working/submission.csv  (280 filas)\n",
      "\n",
      "── Evaluacion interna ──────────────────────────────────────\n"
     ]
    }
   ],
   "source": [
    "# H7 AGI Benchmark — Predictor (R)\n",
    "# Vietoris-Rips inspirado: bola epsilon sobre distancia dual\n",
    "# Euclidiana + Mahalanobis con expansion adaptativa.\n",
    "\n",
    "setwd(\"/kaggle/input/datasets/jakomina/database\")\n",
    ".libPaths(c(\"/home/runner/R/library\", .libPaths()))\n",
    "suppressMessages({\n",
    "  library(MASS)\n",
    "})\n",
    "\n",
    "# ── Constantes H7 ─────────────────────────────────────────────────────────────\n",
    "PHI       <- (1 + sqrt(5)) / 2\n",
    "PSI_1     <- abs(cos(pi * PHI))\n",
    "DRIFT_072 <- 7 - 2 * pi\n",
    "\n",
    "# ── Features por track ────────────────────────────────────────────────────────\n",
    "TRACK_FEATURES <- list(\n",
    "  learning            = c(\"phi_i\", \"phi_j\", \"level_k\", \"n_index\"),\n",
    "  metacognition       = c(\"amplitude\", \"psi1\"),\n",
    "  attention           = c(\"epsilon_density\", \"active_trits\"),\n",
    "  executive_functions = c(\"level_k\", \"amplitude\", \"re_i\"),\n",
    "  social_cognition    = c(\"amp_a\", \"amp_b\")\n",
    ")\n",
    "\n",
    "ALPHA      <- 0.5   # peso Euclidiana vs Mahalanobis\n",
    "EPS_PCTILE <- 20    # percentil para calibrar epsilon\n",
    "EPS_EXPAND <- 1.5   # factor de expansion si la bola queda vacia\n",
    "MAX_EXPAND <- 10    # maximas expansiones antes de fallback\n",
    "\n",
    "\n",
    "# ── Escalado (StandardScaler equivalente) ─────────────────────────────────────\n",
    "std_scale <- function(X_train, X_test) {\n",
    "  mu  <- colMeans(X_train)\n",
    "  sd  <- apply(X_train, 2, sd) + 1e-9\n",
    "  list(\n",
    "    X_tr = sweep(sweep(X_train, 2, mu, \"-\"), 2, sd, \"/\"),\n",
    "    X_te = sweep(sweep(X_test,  2, mu, \"-\"), 2, sd, \"/\")\n",
    "  )\n",
    "}\n",
    "\n",
    "\n",
    "# ── Precision matrix robusta (Sigma^-1) ───────────────────────────────────────\n",
    "precision_mat <- function(X) {\n",
    "  tryCatch({\n",
    "    S <- cov(X) + diag(1e-6, ncol(X))\n",
    "    solve(S)\n",
    "  }, error = function(e) {\n",
    "    ginv(cov(X) + diag(1e-6, ncol(X)))\n",
    "  })\n",
    "}\n",
    "\n",
    "\n",
    "# ── Distancia dual (n_test x n_train) ─────────────────────────────────────────\n",
    "dual_distance <- function(X_tr, X_te, VI, alpha = ALPHA) {\n",
    "  n_te <- nrow(X_te)\n",
    "  n_tr <- nrow(X_tr)\n",
    "\n",
    "  # Euclidiana\n",
    "  eucl <- matrix(0, n_te, n_tr)\n",
    "  for (i in seq_len(n_te)) {\n",
    "    diff     <- sweep(X_tr, 2, X_te[i, ], \"-\")\n",
    "    eucl[i,] <- sqrt(rowSums(diff^2))\n",
    "  }\n",
    "\n",
    "  # Mahalanobis\n",
    "  maha <- matrix(0, n_te, n_tr)\n",
    "  for (i in seq_len(n_te)) {\n",
    "    diff     <- sweep(X_tr, 2, X_te[i, ], \"-\")\n",
    "    maha[i,] <- sqrt(pmax(rowSums((diff %*% VI) * diff), 0))\n",
    "  }\n",
    "\n",
    "  alpha * eucl + (1 - alpha) * maha\n",
    "}\n",
    "\n",
    "\n",
    "# ── Calibrar epsilon desde distancias train-train ─────────────────────────────\n",
    "calibrate_eps <- function(D_tt, pctile = EPS_PCTILE) {\n",
    "  diag(D_tt) <- NA\n",
    "  as.numeric(quantile(D_tt, pctile / 100, na.rm = TRUE))\n",
    "}\n",
    "\n",
    "\n",
    "# ── Bola VR: indices + pesos ──────────────────────────────────────────────────\n",
    "vr_ball <- function(d_row, eps) {\n",
    "  current_eps <- eps\n",
    "  for (k in seq_len(MAX_EXPAND)) {\n",
    "    idx <- which(d_row <= current_eps)\n",
    "    if (length(idx) > 0) {\n",
    "      w <- 1 / (d_row[idx] + 1e-9)\n",
    "      return(list(idx = idx, w = w / sum(w)))\n",
    "    }\n",
    "    current_eps <- current_eps * EPS_EXPAND\n",
    "  }\n",
    "  # fallback: vecino mas cercano\n",
    "  nn <- which.min(d_row)\n",
    "  list(idx = nn, w = 1.0)\n",
    "}\n",
    "\n",
    "\n",
    "# ── Parsers ───────────────────────────────────────────────────────────────────\n",
    "parse_meta <- function(t) {\n",
    "  parts <- strsplit(trimws(t), \" \")[[1]]\n",
    "  dev   <- as.numeric(sub(\"deviation=\", \"\", parts[1]))\n",
    "  conf  <- sub(\"confidence=\", \"\", parts[2])\n",
    "  list(dev = dev, conf = conf)\n",
    "}\n",
    "\n",
    "parse_vec7 <- function(t) {\n",
    "  cleaned <- gsub(\"[\\\\[\\\\]\\\\s]\", \"\", t, perl = TRUE)\n",
    "  vals    <- suppressWarnings(as.numeric(strsplit(cleaned, \",\")[[1]]))\n",
    "  vals\n",
    "}\n",
    "\n",
    "\n",
    "# ── Voto mayoritario ponderado ────────────────────────────────────────────────\n",
    "weighted_vote <- function(targets, weights) {\n",
    "  tab <- tapply(weights, targets, sum)\n",
    "  names(tab)[which.max(tab)]\n",
    "}\n",
    "\n",
    "\n",
    "# ── Predictor por track ───────────────────────────────────────────────────────\n",
    "predict_track <- function(track, train, test) {\n",
    "  feats  <- TRACK_FEATURES[[track]]\n",
    "  tr_sub <- train[train$track == track, ]\n",
    "  te_sub <- test[test$track   == track, ]\n",
    "\n",
    "  if (nrow(tr_sub) == 0 || nrow(te_sub) == 0) return(data.frame())\n",
    "\n",
    "  # Reemplazar NA por 0\n",
    "  tr_sub[, feats] <- lapply(tr_sub[, feats], function(x) ifelse(is.na(x), 0, as.numeric(x)))\n",
    "  te_sub[, feats] <- lapply(te_sub[, feats], function(x) ifelse(is.na(x), 0, as.numeric(x)))\n",
    "\n",
    "  scaled   <- std_scale(as.matrix(tr_sub[, feats]), as.matrix(te_sub[, feats]))\n",
    "  X_tr     <- scaled$X_tr\n",
    "  X_te     <- scaled$X_te\n",
    "\n",
    "  VI  <- precision_mat(X_tr)\n",
    "  D_tt <- dual_distance(X_tr, X_tr, VI)\n",
    "  eps  <- calibrate_eps(D_tt, EPS_PCTILE)\n",
    "  D    <- dual_distance(X_tr, X_te, VI)\n",
    "\n",
    "  avg_ball <- mean(sapply(seq_len(nrow(X_te)), function(i) sum(D[i,] <= eps)))\n",
    "  cat(sprintf(\"    epsilon=%.4f  |  vecinos promedio: %.1f\\n\", eps, avg_ball))\n",
    "\n",
    "  preds <- character(nrow(te_sub))\n",
    "\n",
    "  # ── Learning ────────────────────────────────────────────────────────────\n",
    "  if (track == \"learning\") {\n",
    "    y <- as.numeric(tr_sub$target_numeric)\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b    <- vr_ball(D[i,], eps)\n",
    "      pred <- sum(b$w * y[b$idx])\n",
    "      preds[i] <- sprintf(\"%.8f\", pred)\n",
    "    }\n",
    "\n",
    "  # ── Metacognition ────────────────────────────────────────────────────────\n",
    "  } else if (track == \"metacognition\") {\n",
    "    parsed    <- lapply(tr_sub$target, parse_meta)\n",
    "    devs      <- sapply(parsed, `[[`, \"dev\")\n",
    "    confs     <- sapply(parsed, `[[`, \"conf\")\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b         <- vr_ball(D[i,], eps)\n",
    "      pred_dev  <- sum(b$w * devs[b$idx])\n",
    "      pred_conf <- weighted_vote(confs[b$idx], b$w)\n",
    "      preds[i]  <- sprintf(\"deviation=%.6f confidence=%s\", pred_dev, pred_conf)\n",
    "    }\n",
    "\n",
    "  # ── Attention ────────────────────────────────────────────────────────────\n",
    "  } else if (track == \"attention\") {\n",
    "    vecs <- t(sapply(tr_sub$target, parse_vec7))\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b      <- vr_ball(D[i,], eps)\n",
    "      pred_v <- colSums(vecs[b$idx, , drop = FALSE] * b$w)\n",
    "      preds[i] <- paste0(\"[\", paste(round(pred_v, 4), collapse = \", \"), \"]\")\n",
    "    }\n",
    "\n",
    "  # ── Executive functions ──────────────────────────────────────────────────\n",
    "  } else if (track == \"executive_functions\") {\n",
    "    targets <- as.character(tr_sub$target)\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b        <- vr_ball(D[i,], eps)\n",
    "      preds[i] <- weighted_vote(targets[b$idx], b$w)\n",
    "    }\n",
    "\n",
    "  # ── Social cognition ─────────────────────────────────────────────────────\n",
    "  } else if (track == \"social_cognition\") {\n",
    "    targets <- as.character(tr_sub$target)\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b        <- vr_ball(D[i,], eps)\n",
    "      preds[i] <- weighted_vote(targets[b$idx], b$w)\n",
    "    }\n",
    "  }\n",
    "\n",
    "  data.frame(id = te_sub$id, target = preds, stringsAsFactors = FALSE)\n",
    "}\n",
    "\n",
    "\n",
    "# ── Evaluacion interna ────────────────────────────────────────────────────────\n",
    "evaluate <- function(submission) {\n",
    "  ans_path <- \"/kaggle/input/notebooks/jakomina/attention-ipynb/submission\"\n",
    "  if (!file.exists(ans_path)) {\n",
    "    cat(\"  (test_with_answers.csv no encontrado)\\n\")\n",
    "    return(invisible(NULL))\n",
    "  }\n",
    "\n",
    "  answers <- read.csv(ans_path, stringsAsFactors = FALSE)\n",
    "  m       <- merge(answers, submission, by = \"id\", suffixes = c(\"_true\", \"_pred\"))\n",
    "\n",
    "  cat(\"\\n── Evaluacion interna ──────────────────────────────────────\\n\")\n",
    "\n",
    "  # Learning\n",
    "  sub <- m[m$track == \"learning\", ]\n",
    "  if (nrow(sub) > 0) {\n",
    "    mae <- mean(abs(sub$target_numeric - as.numeric(sub$target_pred)))\n",
    "    cat(sprintf(\"  learning            MAE          : %.6f\\n\", mae))\n",
    "  }\n",
    "\n",
    "  # Metacognition\n",
    "  sub <- m[m$track == \"metacognition\", ]\n",
    "  if (nrow(sub) > 0) {\n",
    "    dt  <- sapply(sub$target_true, function(t) parse_meta(t)$dev)\n",
    "    dp  <- sapply(sub$target_pred, function(t) parse_meta(t)$dev)\n",
    "    ct  <- sapply(sub$target_true, function(t) parse_meta(t)$conf)\n",
    "    cp  <- sapply(sub$target_pred, function(t) parse_meta(t)$conf)\n",
    "    cat(sprintf(\"  metacognition       MAE dev      : %.6f  |  conf acc: %.2f%%\\n\",\n",
    "                mean(abs(dt - dp)), 100 * mean(ct == cp)))\n",
    "  }\n",
    "\n",
    "  # Attention\n",
    "  sub <- m[m$track == \"attention\", ]\n",
    "  if (nrow(sub) > 0) {\n",
    "    sims <- mapply(function(t, p) {\n",
    "      vt <- suppressWarnings(parse_vec7(t))\n",
    "      vp <- suppressWarnings(parse_vec7(p))\n",
    "      if (any(is.na(vt)) || any(is.na(vp))) return(NA_real_)\n",
    "      nt <- sqrt(sum(vt^2)); np_ <- sqrt(sum(vp^2))\n",
    "      if (nt > 0 && np_ > 0) sum(vt * vp) / (nt * np_) else NA_real_\n",
    "    }, sub$target_true, sub$target_pred)\n",
    "    cat(sprintf(\"  attention           cosine sim   : %.4f\\n\", mean(sims, na.rm = TRUE)))\n",
    "  }\n",
    "\n",
    "  # Executive + Social\n",
    "  for (track in c(\"executive_functions\", \"social_cognition\")) {\n",
    "    sub <- m[m$track == track, ]\n",
    "    if (nrow(sub) > 0) {\n",
    "      acc <- mean(sub$target_true == sub$target_pred)\n",
    "      cat(sprintf(\"  %-22s  exact match  : %.2f%%\\n\", track, 100 * acc))\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "\n",
    "# ── Main ──────────────────────────────────────────────────────────────────────\n",
    "main <- function() {\n",
    "  train <- read.csv(\"/kaggle/input/datasets/jakomina/database/train.csv\", stringsAsFactors = FALSE)\n",
    "  test  <- read.csv(\"/kaggle/input/datasets/jakomina/database/test.csv\",  stringsAsFactors = FALSE)\n",
    "\n",
    "  cat(sprintf(\"Train: %d filas | Test: %d filas\\n\", nrow(train), nrow(test)))\n",
    "  cat(sprintf(\"Metodo: VR-ball  alpha=%.1f  eps-pctile=%d%%  expand x%.1f\\n\\n\",\n",
    "              ALPHA, EPS_PCTILE, EPS_EXPAND))\n",
    "\n",
    "  all_preds <- list()\n",
    "  for (track in names(TRACK_FEATURES)) {\n",
    "    cat(sprintf(\"  [%s]\\n\", track))\n",
    "    p <- predict_track(track, train, test)\n",
    "    cat(sprintf(\"    -> %d predicciones\\n\\n\", nrow(p)))\n",
    "    all_preds[[track]] <- p\n",
    "  }\n",
    "\n",
    "  submission <- do.call(rbind, all_preds)\n",
    "\n",
    "  # Reordenar segun sample_submission\n",
    "  sample_sub <- read.csv(\"/kaggle/input/datasets/jakomina/database/sample_submission.csv\",\n",
    "                         stringsAsFactors = FALSE)\n",
    "  submission <- merge(sample_sub[\"id\"], submission, by = \"id\", all.x = TRUE)\n",
    "  submission$target[is.na(submission$target)] <- \"0.00000000\"\n",
    "\n",
    "  out <- \"/kaggle/working/submission.csv\"\n",
    "  write.csv(submission, out, row.names = FALSE, quote = TRUE)\n",
    "  cat(sprintf(\"Submission -> %s  (%d filas)\\n\", out, nrow(submission)))\n",
    "\n",
    "  evaluate(submission)\n",
    "}\n",
    "\n",
    "main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b1058343",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-25T15:02:39.582980Z",
     "iopub.status.busy": "2026-03-25T15:02:39.550505Z",
     "iopub.status.idle": "2026-03-25T15:02:40.049872Z",
     "shell.execute_reply": "2026-03-25T15:02:40.047249Z"
    },
    "papermill": {
     "duration": 0.511909,
     "end_time": "2026-03-25T15:02:40.057695",
     "exception": false,
     "start_time": "2026-03-25T15:02:39.545786",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Procesando 5 pistas de AGI Benchmark...\n",
      "  Ejecutando Track: [learning]\n",
      "    epsilon=1.7969  |  vecinos promedio: 49.0\n",
      "  Ejecutando Track: [metacognition]\n",
      "    epsilon=0.3103  |  vecinos promedio: 46.7\n",
      "  Ejecutando Track: [attention]\n",
      "    epsilon=0.5206  |  vecinos promedio: 39.3\n",
      "  Ejecutando Track: [executive_functions]\n",
      "    epsilon=1.3419  |  vecinos promedio: 48.8\n",
      "  Ejecutando Track: [social_cognition]\n",
      "    epsilon=0.9595  |  vecinos promedio: 51.5\n",
      "\n",
      "[SUCCESS] Archivo generado en: /kaggle/working/submission.csv\n"
     ]
    }
   ],
   "source": [
    "# ── Ajuste de Robustez en Distancia y Salida ───────────────────────────\n",
    "\n",
    "# Modificación en precision_mat para asegurar estabilidad numérica\n",
    "precision_mat <- function(X) {\n",
    "  # Usamos una regularización más fuerte basada en el espectro de la matriz\n",
    "  S <- cov(X)\n",
    "  n_col <- ncol(X)\n",
    "  # Ridge adaptativo\n",
    "  lambda <- 1e-4 * max(diag(S))\n",
    "  tryCatch({\n",
    "    solve(S + diag(lambda, n_col))\n",
    "  }, error = function(e) {\n",
    "    # Fallback a pseudo-inversa de Penrose-Moore\n",
    "    ginv(S + diag(lambda, n_col))\n",
    "  })\n",
    "}\n",
    "\n",
    "# ── Bloque Main Optimizado para Competencia ───────────────────────────\n",
    "main <- function() {\n",
    "  # Carga de archivos con rutas relativas ajustadas\n",
    "  path_base <- \"/kaggle/input/datasets/jakomina/database/\"\n",
    "  train <- read.csv(paste0(path_base, \"train.csv\"), stringsAsFactors = FALSE)\n",
    "  test  <- read.csv(paste0(path_base, \"test.csv\"),  stringsAsFactors = FALSE)\n",
    "  sample_sub <- read.csv(paste0(path_base, \"sample_submission.csv\"), stringsAsFactors = FALSE)\n",
    "\n",
    "  cat(sprintf(\"Procesando %d pistas de AGI Benchmark...\\n\", length(TRACK_FEATURES)))\n",
    "\n",
    "  all_preds_list <- list()\n",
    "  for (track in names(TRACK_FEATURES)) {\n",
    "    cat(sprintf(\"  Ejecutando Track: [%s]\\n\", track))\n",
    "    p <- predict_track(track, train, test)\n",
    "    if(nrow(p) > 0) all_preds_list[[track]] <- p\n",
    "  }\n",
    "\n",
    "  # Combinar todas las predicciones de los tracks\n",
    "  submission_raw <- do.call(rbind, all_preds_list)\n",
    "\n",
    "  # CRITICAL KAGGLE STEP: Asegurar orden idéntico al sample_submission\n",
    "  # Esto evita errores de desalineación en el sistema de puntuación\n",
    "  final_submission <- data.frame(id = sample_sub$id, stringsAsFactors = FALSE)\n",
    "  final_submission <- merge(final_submission, submission_raw, by = \"id\", all.x = TRUE)\n",
    "  \n",
    "  # Imputación de seguridad para valores faltantes (Edge cases)\n",
    "  final_submission$target[is.na(final_submission$target)] <- \"0.0\"\n",
    "\n",
    "  # Escritura final - IMPORTANTE: quote=TRUE suele ser necesario si \n",
    "  # los targets contienen comas (como en el track de attention [0.1, 0.2])\n",
    "  out_path <- \"/kaggle/working/submission.csv\"\n",
    "  write.csv(final_submission, out_path, row.names = FALSE, quote = TRUE)\n",
    "  \n",
    "  cat(sprintf(\"\\n[SUCCESS] Archivo generado en: %s\\n\", out_path))\n",
    "  \n",
    "  # Validación de consistencia de filas\n",
    "  if(nrow(final_submission) != nrow(sample_sub)) {\n",
    "    warning(\"¡ALERTA! El número de filas no coincide con el formato requerido.\")\n",
    "  }\n",
    "}\n",
    "\n",
    "main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d815c9a9",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-25T15:02:40.068879Z",
     "iopub.status.busy": "2026-03-25T15:02:40.066654Z",
     "iopub.status.idle": "2026-03-25T15:02:40.708667Z",
     "shell.execute_reply": "2026-03-25T15:02:40.706489Z"
    },
    "papermill": {
     "duration": 0.650907,
     "end_time": "2026-03-25T15:02:40.711376",
     "exception": false,
     "start_time": "2026-03-25T15:02:40.060469",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing 5 AGI Benchmark tracks...\n",
      "  Executing Track: [learning]\n",
      "    epsilon=1.7969  |  average neighbors: 49.0\n",
      "  Executing Track: [metacognition]\n",
      "    epsilon=0.3103  |  average neighbors: 46.7\n",
      "  Executing Track: [attention]\n",
      "    epsilon=0.5206  |  average neighbors: 39.3\n",
      "  Executing Track: [executive_functions]\n",
      "    epsilon=1.3419  |  average neighbors: 48.8\n",
      "  Executing Track: [social_cognition]\n",
      "    epsilon=0.9595  |  average neighbors: 51.5\n",
      "\n",
      "[SUCCESS] File generated at: /kaggle/working/submission.csv\n",
      "\n",
      "── Internal evaluation ──────────────────────────────────────\n"
     ]
    }
   ],
   "source": [
    "# H7 AGI Benchmark — Predictor (R)\n",
    "# Vietoris-Rips inspired: epsilon ball over dual distance\n",
    "# Euclidean + Mahalanobis with adaptive expansion.\n",
    "\n",
    "setwd(\"/kaggle/input/datasets/jakomina/database\")\n",
    ".libPaths(c(\"/home/runner/R/library\", .libPaths()))\n",
    "suppressMessages({\n",
    "  library(MASS)\n",
    "})\n",
    "\n",
    "# ── H7 Constants ──────────────────────────────────────────────────────────────\n",
    "PHI       <- (1 + sqrt(5)) / 2\n",
    "PSI_1     <- abs(cos(pi * PHI))\n",
    "DRIFT_072 <- 7 - 2 * pi\n",
    "\n",
    "# ── Features per track ────────────────────────────────────────────────────────\n",
    "TRACK_FEATURES <- list(\n",
    "  learning            = c(\"phi_i\", \"phi_j\", \"level_k\", \"n_index\"),\n",
    "  metacognition       = c(\"amplitude\", \"psi1\"),\n",
    "  attention           = c(\"epsilon_density\", \"active_trits\"),\n",
    "  executive_functions = c(\"level_k\", \"amplitude\", \"re_i\"),\n",
    "  social_cognition    = c(\"amp_a\", \"amp_b\")\n",
    ")\n",
    "\n",
    "ALPHA      <- 0.5   # weight Euclidean vs Mahalanobis\n",
    "EPS_PCTILE <- 20    # percentile to calibrate epsilon\n",
    "EPS_EXPAND <- 1.5   # expansion factor if ball is empty\n",
    "MAX_EXPAND <- 10    # max expansions before fallback\n",
    "\n",
    "\n",
    "# ── Scaling (StandardScaler equivalent) ───────────────────────────────────────\n",
    "std_scale <- function(X_train, X_test) {\n",
    "  mu  <- colMeans(X_train)\n",
    "  sd  <- apply(X_train, 2, sd) + 1e-9\n",
    "  list(\n",
    "    X_tr = sweep(sweep(X_train, 2, mu, \"-\"), 2, sd, \"/\"),\n",
    "    X_te = sweep(sweep(X_test,  2, mu, \"-\"), 2, sd, \"/\")\n",
    "  )\n",
    "}\n",
    "\n",
    "# ── Robust precision matrix (Sigma^-1) ────────────────────────────────────────\n",
    "precision_mat <- function(X) {\n",
    "  # Use spectrum-based regularization for stronger stability\n",
    "  S <- cov(X)\n",
    "  n_col <- ncol(X)\n",
    "  # Adaptive ridge\n",
    "  lambda <- 1e-4 * max(diag(S))\n",
    "  tryCatch({\n",
    "    solve(S + diag(lambda, n_col))\n",
    "  }, error = function(e) {\n",
    "    # Fallback to Penrose-Moore pseudo-inverse\n",
    "    ginv(S + diag(lambda, n_col))\n",
    "  })\n",
    "}\n",
    "\n",
    "# ── Dual distance (n_test x n_train) ──────────────────────────────────────────\n",
    "dual_distance <- function(X_tr, X_te, VI, alpha = ALPHA) {\n",
    "  n_te <- nrow(X_te)\n",
    "  n_tr <- nrow(X_tr)\n",
    "\n",
    "  # Euclidean\n",
    "  eucl <- matrix(0, n_te, n_tr)\n",
    "  for (i in seq_len(n_te)) {\n",
    "    diff     <- sweep(X_tr, 2, X_te[i, ], \"-\")\n",
    "    eucl[i,] <- sqrt(rowSums(diff^2))\n",
    "  }\n",
    "\n",
    "  # Mahalanobis\n",
    "  maha <- matrix(0, n_te, n_tr)\n",
    "  for (i in seq_len(n_te)) {\n",
    "    diff     <- sweep(X_tr, 2, X_te[i, ], \"-\")\n",
    "    maha[i,] <- sqrt(pmax(rowSums((diff %*% VI) * diff), 0))\n",
    "  }\n",
    "\n",
    "  alpha * eucl + (1 - alpha) * maha\n",
    "}\n",
    "\n",
    "\n",
    "# ── Calibrate epsilon from train-train distances ────────────────────────────\n",
    "calibrate_eps <- function(D_tt, pctile = EPS_PCTILE) {\n",
    "  diag(D_tt) <- NA\n",
    "  as.numeric(quantile(D_tt, pctile / 100, na.rm = TRUE))\n",
    "}\n",
    "\n",
    "\n",
    "# ── VR Ball: indices + weights ────────────────────────────────────────────────\n",
    "vr_ball <- function(d_row, eps) {\n",
    "  current_eps <- eps\n",
    "  for (k in seq_len(MAX_EXPAND)) {\n",
    "    idx <- which(d_row <= current_eps)\n",
    "    if (length(idx) > 0) {\n",
    "      w <- 1 / (d_row[idx] + 1e-9)\n",
    "      return(list(idx = idx, w = w / sum(w)))\n",
    "    }\n",
    "    current_eps <- current_eps * EPS_EXPAND\n",
    "  }\n",
    "  # fallback: nearest neighbor\n",
    "  nn <- which.min(d_row)\n",
    "  list(idx = nn, w = 1.0)\n",
    "}\n",
    "\n",
    "\n",
    "# ── Parsers ───────────────────────────────────────────────────────────────────\n",
    "parse_meta <- function(t) {\n",
    "  parts <- strsplit(trimws(t), \" \")[[1]]\n",
    "  dev   <- as.numeric(sub(\"deviation=\", \"\", parts[1]))\n",
    "  conf  <- sub(\"confidence=\", \"\", parts[2])\n",
    "  list(dev = dev, conf = conf)\n",
    "}\n",
    "\n",
    "parse_vec7 <- function(t) {\n",
    "  cleaned <- gsub(\"[\\\\[\\\\]\\\\s]\", \"\", t, perl = TRUE)\n",
    "  vals    <- suppressWarnings(as.numeric(strsplit(cleaned, \",\")[[1]]))\n",
    "  vals\n",
    "}\n",
    "\n",
    "\n",
    "# ── Weighted majority vote ────────────────────────────────────────────────────\n",
    "weighted_vote <- function(targets, weights) {\n",
    "  tab <- tapply(weights, targets, sum)\n",
    "  names(tab)[which.max(tab)]\n",
    "}\n",
    "\n",
    "\n",
    "# ── Track predictor ───────────────────────────────────────────────────────────\n",
    "predict_track <- function(track, train, test) {\n",
    "  feats  <- TRACK_FEATURES[[track]]\n",
    "  tr_sub <- train[train$track == track, ]\n",
    "  te_sub <- test[test$track   == track, ]\n",
    "\n",
    "  if (nrow(tr_sub) == 0 || nrow(te_sub) == 0) return(data.frame())\n",
    "\n",
    "  # Replace NA with 0\n",
    "  tr_sub[, feats] <- lapply(tr_sub[, feats], function(x) ifelse(is.na(x), 0, as.numeric(x)))\n",
    "  te_sub[, feats] <- lapply(te_sub[, feats], function(x) ifelse(is.na(x), 0, as.numeric(x)))\n",
    "\n",
    "  scaled   <- std_scale(as.matrix(tr_sub[, feats]), as.matrix(te_sub[, feats]))\n",
    "  X_tr     <- scaled$X_tr\n",
    "  X_te     <- scaled$X_te\n",
    "\n",
    "  VI  <- precision_mat(X_tr)\n",
    "  D_tt <- dual_distance(X_tr, X_tr, VI)\n",
    "  eps  <- calibrate_eps(D_tt, EPS_PCTILE)\n",
    "  D    <- dual_distance(X_tr, X_te, VI)\n",
    "\n",
    "  avg_ball <- mean(sapply(seq_len(nrow(X_te)), function(i) sum(D[i,] <= eps)))\n",
    "  cat(sprintf(\"    epsilon=%.4f  |  average neighbors: %.1f\\n\", eps, avg_ball))\n",
    "\n",
    "  preds <- character(nrow(te_sub))\n",
    "\n",
    "  # ── Learning ────────────────────────────────────────────────────────────\n",
    "  if (track == \"learning\") {\n",
    "    y <- as.numeric(tr_sub$target_numeric)\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b    <- vr_ball(D[i,], eps)\n",
    "      pred <- sum(b$w * y[b$idx])\n",
    "      preds[i] <- sprintf(\"%.8f\", pred)\n",
    "    }\n",
    "\n",
    "  # ── Metacognition ────────────────────────────────────────────────────────\n",
    "  } else if (track == \"metacognition\") {\n",
    "    parsed    <- lapply(tr_sub$target, parse_meta)\n",
    "    devs      <- sapply(parsed, `[[`, \"dev\")\n",
    "    confs     <- sapply(parsed, `[[`, \"conf\")\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b         <- vr_ball(D[i,], eps)\n",
    "      pred_dev  <- sum(b$w * devs[b$idx])\n",
    "      pred_conf <- weighted_vote(confs[b$idx], b$w)\n",
    "      preds[i]  <- sprintf(\"deviation=%.6f confidence=%s\", pred_dev, pred_conf)\n",
    "    }\n",
    "\n",
    "  # ── Attention ────────────────────────────────────────────────────────────\n",
    "  } else if (track == \"attention\") {\n",
    "    vecs <- t(sapply(tr_sub$target, parse_vec7))\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b      <- vr_ball(D[i,], eps)\n",
    "      pred_v <- colSums(vecs[b$idx, , drop = FALSE] * b$w)\n",
    "      preds[i] <- paste0(\"[\", paste(round(pred_v, 4), collapse = \", \"), \"]\")\n",
    "    }\n",
    "\n",
    "  # ── Executive functions ──────────────────────────────────────────────────\n",
    "  } else if (track == \"executive_functions\") {\n",
    "    targets <- as.character(tr_sub$target)\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b        <- vr_ball(D[i,], eps)\n",
    "      preds[i] <- weighted_vote(targets[b$idx], b$w)\n",
    "    }\n",
    "\n",
    "  # ── Social cognition ─────────────────────────────────────────────────────\n",
    "  } else if (track == \"social_cognition\") {\n",
    "    targets <- as.character(tr_sub$target)\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b        <- vr_ball(D[i,], eps)\n",
    "      preds[i] <- weighted_vote(targets[b$idx], b$w)\n",
    "    }\n",
    "  }\n",
    "\n",
    "  data.frame(id = te_sub$id, target = preds, stringsAsFactors = FALSE)\n",
    "}\n",
    "\n",
    "\n",
    "# ── Internal evaluation ───────────────────────────────────────────────────────\n",
    "evaluate <- function(submission) {\n",
    "  ans_path <- \"/kaggle/input/notebooks/jakomina/attention-ipynb/submission\"\n",
    "  if (!file.exists(ans_path)) {\n",
    "    cat(\"  (test_with_answers.csv not found)\\n\")\n",
    "    return(invisible(NULL))\n",
    "  }\n",
    "\n",
    "  answers <- read.csv(ans_path, stringsAsFactors = FALSE)\n",
    "  m       <- merge(answers, submission, by = \"id\", suffixes = c(\"_true\", \"_pred\"))\n",
    "\n",
    "  cat(\"\\n── Internal evaluation ──────────────────────────────────────\\n\")\n",
    "\n",
    "  # Learning\n",
    "  sub <- m[m$track == \"learning\", ]\n",
    "  if (nrow(sub) > 0) {\n",
    "    mae <- mean(abs(sub$target_numeric - as.numeric(sub$target_pred)))\n",
    "    cat(sprintf(\"  learning             MAE          : %.6f\\n\", mae))\n",
    "  }\n",
    "\n",
    "  # Metacognition\n",
    "  sub <- m[m$track == \"metacognition\", ]\n",
    "  if (nrow(sub) > 0) {\n",
    "    dt  <- sapply(sub$target_true, function(t) parse_meta(t)$dev)\n",
    "    dp  <- sapply(sub$target_pred, function(t) parse_meta(t)$dev)\n",
    "    ct  <- sapply(sub$target_true, function(t) parse_meta(t)$conf)\n",
    "    cp  <- sapply(sub$target_pred, function(t) parse_meta(t)$conf)\n",
    "    cat(sprintf(\"  metacognition        MAE dev      : %.6f  |  conf acc: %.2f%%\\n\",\n",
    "                mean(abs(dt - dp)), 100 * mean(ct == cp)))\n",
    "  }\n",
    "\n",
    "  # Attention\n",
    "  sub <- m[m$track == \"attention\", ]\n",
    "  if (nrow(sub) > 0) {\n",
    "    sims <- mapply(function(t, p) {\n",
    "      vt <- suppressWarnings(parse_vec7(t))\n",
    "      vp <- suppressWarnings(parse_vec7(p))\n",
    "      if (any(is.na(vt)) || any(is.na(vp))) return(NA_real_)\n",
    "      nt <- sqrt(sum(vt^2)); np_ <- sqrt(sum(vp^2))\n",
    "      if (nt > 0 && np_ > 0) sum(vt * vp) / (nt * np_) else NA_real_\n",
    "    }, sub$target_true, sub$target_pred)\n",
    "    cat(sprintf(\"  attention            cosine sim   : %.4f\\n\", mean(sims, na.rm = TRUE)))\n",
    "  }\n",
    "\n",
    "  # Executive + Social\n",
    "  for (track in c(\"executive_functions\", \"social_cognition\")) {\n",
    "    sub <- m[m$track == track, ]\n",
    "    if (nrow(sub) > 0) {\n",
    "      acc <- mean(sub$target_true == sub$target_pred)\n",
    "      cat(sprintf(\"  %-22s  exact match  : %.2f%%\\n\", track, 100 * acc))\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "# ── Main Block Optimized for Competition ──────────────────────────────────────\n",
    "main <- function() {\n",
    "  # File loading with adjusted relative paths\n",
    "  path_base <- \"/kaggle/input/datasets/jakomina/database/\"\n",
    "  train <- read.csv(paste0(path_base, \"train.csv\"), stringsAsFactors = FALSE)\n",
    "  test  <- read.csv(paste0(path_base, \"test.csv\"),  stringsAsFactors = FALSE)\n",
    "  sample_sub <- read.csv(paste0(path_base, \"sample_submission.csv\"), stringsAsFactors = FALSE)\n",
    "\n",
    "  cat(sprintf(\"Processing %d AGI Benchmark tracks...\\n\", length(TRACK_FEATURES)))\n",
    "\n",
    "  all_preds_list <- list()\n",
    "  for (track in names(TRACK_FEATURES)) {\n",
    "    cat(sprintf(\"  Executing Track: [%s]\\n\", track))\n",
    "    p <- predict_track(track, train, test)\n",
    "    if(nrow(p) > 0) all_preds_list[[track]] <- p\n",
    "  }\n",
    "\n",
    "  # Combine all track predictions\n",
    "  submission_raw <- do.call(rbind, all_preds_list)\n",
    "\n",
    "  # CRITICAL KAGGLE STEP: Ensure identical order to sample_submission\n",
    "  # This prevents misalignment errors in the scoring system\n",
    "  final_submission <- data.frame(id = sample_sub$id, stringsAsFactors = FALSE)\n",
    "  final_submission <- merge(final_submission, submission_raw, by = \"id\", all.x = TRUE)\n",
    "  \n",
    "  # Safety imputation for missing values (Edge cases)\n",
    "  final_submission$target[is.na(final_submission$target)] <- \"0.0\"\n",
    "\n",
    "  # Final write - IMPORTANT: quote=TRUE is usually necessary if \n",
    "  # targets contain commas (like in the attention track [0.1, 0.2])\n",
    "  out_path <- \"/kaggle/working/submission.csv\"\n",
    "  write.csv(final_submission, out_path, row.names = FALSE, quote = TRUE)\n",
    "  \n",
    "  cat(sprintf(\"\\n[SUCCESS] File generated at: %s\\n\", out_path))\n",
    "  \n",
    "  # Row consistency validation\n",
    "  if(nrow(final_submission) != nrow(sample_sub)) {\n",
    "    warning(\"ALERT! Row count does not match required format.\")\n",
    "  } else {\n",
    "    # Call internal evaluator only if format survived\n",
    "    evaluate(final_submission)\n",
    "  }\n",
    "}\n",
    "\n",
    "main()"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "databundleVersionId": 15757621,
     "sourceId": 128852,
     "sourceType": "competition"
    },
    {
     "databundleVersionId": 16149021,
     "datasetId": 9756531,
     "sourceId": 15250896,
     "sourceType": "datasetVersion"
    },
    {
     "databundleVersionId": 13751403,
     "datasetId": 8278084,
     "sourceId": 13071127,
     "sourceType": "datasetVersion"
    },
    {
     "sourceId": 306315782,
     "sourceType": "kernelVersion"
    }
   ],
   "dockerImageVersionId": 31330,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "r",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.4.0"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 5.285007,
   "end_time": "2026-03-25T15:02:40.835645",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-03-25T15:02:35.550638",
   "version": "2.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
