{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b3482197",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-25T17:09:57.180740Z",
     "iopub.status.busy": "2026-03-25T17:09:57.177613Z",
     "iopub.status.idle": "2026-03-25T17:09:58.156829Z",
     "shell.execute_reply": "2026-03-25T17:09:58.154182Z"
    },
    "papermill": {
     "duration": 0.987937,
     "end_time": "2026-03-25T17:09:58.159465",
     "exception": false,
     "start_time": "2026-03-25T17:09:57.171528",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train: 1120 filas | Test: 280 filas\n",
      "Metodo: VR-ball  alpha=0.5  eps-pctile=20%  expand x1.5\n",
      "\n",
      "  [learning]\n",
      "    epsilon=1.7970  |  vecinos promedio: 49.0\n",
      "    -> 60 predicciones\n",
      "\n",
      "  [metacognition]\n",
      "    epsilon=0.3103  |  vecinos promedio: 46.7\n",
      "    -> 60 predicciones\n",
      "\n",
      "  [attention]\n",
      "    epsilon=0.6136  |  vecinos promedio: 36.8\n",
      "    -> 40 predicciones\n",
      "\n",
      "  [executive_functions]\n",
      "    epsilon=1.3419  |  vecinos promedio: 48.8\n",
      "    -> 60 predicciones\n",
      "\n",
      "  [social_cognition]\n",
      "    epsilon=0.9595  |  vecinos promedio: 51.5\n",
      "    -> 60 predicciones\n",
      "\n",
      "Submission -> /kaggle/working/submission.csv  (280 filas)\n",
      "\n",
      "── Evaluacion interna ──────────────────────────────────────\n"
     ]
    }
   ],
   "source": [
    "# First stage experimental\n",
    "# H7 AGI Benchmark — Predictor (R) \n",
    "# Vietoris-Rips inspirado: bola epsilon sobre distancia dual\n",
    "# Euclidiana + Mahalanobis con expansion adaptativa.\n",
    "\n",
    "setwd(\"/kaggle/input/datasets/jakomina/database\")\n",
    ".libPaths(c(\"/home/runner/R/library\", .libPaths()))\n",
    "suppressMessages({\n",
    "  library(MASS)\n",
    "})\n",
    "\n",
    "# ── Constantes H7 ─────────────────────────────────────────────────────────────\n",
    "PHI       <- (1 + sqrt(5)) / 2\n",
    "PSI_1     <- abs(cos(pi * PHI))\n",
    "DRIFT_072 <- 7 - 2 * pi\n",
    "\n",
    "# ── Features por track ────────────────────────────────────────────────────────\n",
    "TRACK_FEATURES <- list(\n",
    "  learning            = c(\"phi_i\", \"phi_j\", \"level_k\", \"n_index\"),\n",
    "  metacognition       = c(\"amplitude\", \"psi1\"),\n",
    "  attention           = c(\"epsilon_density\", \"active_trits\"),\n",
    "  executive_functions = c(\"level_k\", \"amplitude\", \"re_i\"),\n",
    "  social_cognition    = c(\"amp_a\", \"amp_b\")\n",
    ")\n",
    "\n",
    "ALPHA      <- 0.5   # peso Euclidiana vs Mahalanobis\n",
    "EPS_PCTILE <- 20    # percentil para calibrar epsilon\n",
    "EPS_EXPAND <- 1.5   # factor de expansion si la bola queda vacia\n",
    "MAX_EXPAND <- 10    # maximas expansiones antes de fallback\n",
    "\n",
    "\n",
    "# ── Escalado (StandardScaler equivalente) ─────────────────────────────────────\n",
    "std_scale <- function(X_train, X_test) {\n",
    "  mu  <- colMeans(X_train)\n",
    "  sd  <- apply(X_train, 2, sd) + 1e-9\n",
    "  list(\n",
    "    X_tr = sweep(sweep(X_train, 2, mu, \"-\"), 2, sd, \"/\"),\n",
    "    X_te = sweep(sweep(X_test,  2, mu, \"-\"), 2, sd, \"/\")\n",
    "  )\n",
    "}\n",
    "\n",
    "\n",
    "# ── Precision matrix robusta (Sigma^-1) ───────────────────────────────────────\n",
    "precision_mat <- function(X) {\n",
    "  tryCatch({\n",
    "    S <- cov(X) + diag(1e-6, ncol(X))\n",
    "    solve(S)\n",
    "  }, error = function(e) {\n",
    "    ginv(cov(X) + diag(1e-6, ncol(X)))\n",
    "  })\n",
    "}\n",
    "\n",
    "\n",
    "# ── Distancia dual (n_test x n_train) ─────────────────────────────────────────\n",
    "dual_distance <- function(X_tr, X_te, VI, alpha = ALPHA) {\n",
    "  n_te <- nrow(X_te)\n",
    "  n_tr <- nrow(X_tr)\n",
    "\n",
    "  # Euclidiana\n",
    "  eucl <- matrix(0, n_te, n_tr)\n",
    "  for (i in seq_len(n_te)) {\n",
    "    diff     <- sweep(X_tr, 2, X_te[i, ], \"-\")\n",
    "    eucl[i,] <- sqrt(rowSums(diff^2))\n",
    "  }\n",
    "\n",
    "  # Mahalanobis\n",
    "  maha <- matrix(0, n_te, n_tr)\n",
    "  for (i in seq_len(n_te)) {\n",
    "    diff     <- sweep(X_tr, 2, X_te[i, ], \"-\")\n",
    "    maha[i,] <- sqrt(pmax(rowSums((diff %*% VI) * diff), 0))\n",
    "  }\n",
    "\n",
    "  alpha * eucl + (1 - alpha) * maha\n",
    "}\n",
    "\n",
    "\n",
    "# ── Calibrar epsilon desde distancias train-train ─────────────────────────────\n",
    "calibrate_eps <- function(D_tt, pctile = EPS_PCTILE) {\n",
    "  diag(D_tt) <- NA\n",
    "  as.numeric(quantile(D_tt, pctile / 100, na.rm = TRUE))\n",
    "}\n",
    "\n",
    "\n",
    "# ── Bola VR: indices + pesos ──────────────────────────────────────────────────\n",
    "vr_ball <- function(d_row, eps) {\n",
    "  current_eps <- eps\n",
    "  for (k in seq_len(MAX_EXPAND)) {\n",
    "    idx <- which(d_row <= current_eps)\n",
    "    if (length(idx) > 0) {\n",
    "      w <- 1 / (d_row[idx] + 1e-9)\n",
    "      return(list(idx = idx, w = w / sum(w)))\n",
    "    }\n",
    "    current_eps <- current_eps * EPS_EXPAND\n",
    "  }\n",
    "  # fallback: vecino mas cercano\n",
    "  nn <- which.min(d_row)\n",
    "  list(idx = nn, w = 1.0)\n",
    "}\n",
    "\n",
    "\n",
    "# ── Parsers ───────────────────────────────────────────────────────────────────\n",
    "parse_meta <- function(t) {\n",
    "  parts <- strsplit(trimws(t), \" \")[[1]]\n",
    "  dev   <- as.numeric(sub(\"deviation=\", \"\", parts[1]))\n",
    "  conf  <- sub(\"confidence=\", \"\", parts[2])\n",
    "  list(dev = dev, conf = conf)\n",
    "}\n",
    "\n",
    "parse_vec7 <- function(t) {\n",
    "  cleaned <- gsub(\"[\\\\[\\\\]\\\\s]\", \"\", t, perl = TRUE)\n",
    "  vals    <- suppressWarnings(as.numeric(strsplit(cleaned, \",\")[[1]]))\n",
    "  vals\n",
    "}\n",
    "\n",
    "\n",
    "# ── Voto mayoritario ponderado ────────────────────────────────────────────────\n",
    "weighted_vote <- function(targets, weights) {\n",
    "  tab <- tapply(weights, targets, sum)\n",
    "  names(tab)[which.max(tab)]\n",
    "}\n",
    "\n",
    "\n",
    "# ── Predictor por track ───────────────────────────────────────────────────────\n",
    "predict_track <- function(track, train, test) {\n",
    "  feats  <- TRACK_FEATURES[[track]]\n",
    "  tr_sub <- train[train$track == track, ]\n",
    "  te_sub <- test[test$track   == track, ]\n",
    "\n",
    "  if (nrow(tr_sub) == 0 || nrow(te_sub) == 0) return(data.frame())\n",
    "\n",
    "  # Reemplazar NA por 0\n",
    "  tr_sub[, feats] <- lapply(tr_sub[, feats], function(x) ifelse(is.na(x), 0, as.numeric(x)))\n",
    "  te_sub[, feats] <- lapply(te_sub[, feats], function(x) ifelse(is.na(x), 0, as.numeric(x)))\n",
    "\n",
    "  scaled   <- std_scale(as.matrix(tr_sub[, feats]), as.matrix(te_sub[, feats]))\n",
    "  X_tr     <- scaled$X_tr\n",
    "  X_te     <- scaled$X_te\n",
    "\n",
    "  VI  <- precision_mat(X_tr)\n",
    "  D_tt <- dual_distance(X_tr, X_tr, VI)\n",
    "  eps  <- calibrate_eps(D_tt, EPS_PCTILE)\n",
    "  D    <- dual_distance(X_tr, X_te, VI)\n",
    "\n",
    "  avg_ball <- mean(sapply(seq_len(nrow(X_te)), function(i) sum(D[i,] <= eps)))\n",
    "  cat(sprintf(\"    epsilon=%.4f  |  vecinos promedio: %.1f\\n\", eps, avg_ball))\n",
    "\n",
    "  preds <- character(nrow(te_sub))\n",
    "\n",
    "  # ── Learning ────────────────────────────────────────────────────────────\n",
    "  if (track == \"learning\") {\n",
    "    y <- as.numeric(tr_sub$target_numeric)\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b    <- vr_ball(D[i,], eps)\n",
    "      pred <- sum(b$w * y[b$idx])\n",
    "      preds[i] <- sprintf(\"%.8f\", pred)\n",
    "    }\n",
    "\n",
    "  # ── Metacognition ────────────────────────────────────────────────────────\n",
    "  } else if (track == \"metacognition\") {\n",
    "    parsed    <- lapply(tr_sub$target, parse_meta)\n",
    "    devs      <- sapply(parsed, `[[`, \"dev\")\n",
    "    confs     <- sapply(parsed, `[[`, \"conf\")\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b         <- vr_ball(D[i,], eps)\n",
    "      pred_dev  <- sum(b$w * devs[b$idx])\n",
    "      pred_conf <- weighted_vote(confs[b$idx], b$w)\n",
    "      preds[i]  <- sprintf(\"deviation=%.6f confidence=%s\", pred_dev, pred_conf)\n",
    "    }\n",
    "\n",
    "  # ── Attention ────────────────────────────────────────────────────────────\n",
    "  } else if (track == \"attention\") {\n",
    "    vecs <- t(sapply(tr_sub$target, parse_vec7))\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b      <- vr_ball(D[i,], eps)\n",
    "      pred_v <- colSums(vecs[b$idx, , drop = FALSE] * b$w)\n",
    "      preds[i] <- paste0(\"[\", paste(round(pred_v, 4), collapse = \", \"), \"]\")\n",
    "    }\n",
    "\n",
    "  # ── Executive functions ──────────────────────────────────────────────────\n",
    "  } else if (track == \"executive_functions\") {\n",
    "    targets <- as.character(tr_sub$target)\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b        <- vr_ball(D[i,], eps)\n",
    "      preds[i] <- weighted_vote(targets[b$idx], b$w)\n",
    "    }\n",
    "\n",
    "  # ── Social cognition ─────────────────────────────────────────────────────\n",
    "  } else if (track == \"social_cognition\") {\n",
    "    targets <- as.character(tr_sub$target)\n",
    "    for (i in seq_len(nrow(te_sub))) {\n",
    "      b        <- vr_ball(D[i,], eps)\n",
    "      preds[i] <- weighted_vote(targets[b$idx], b$w)\n",
    "    }\n",
    "  }\n",
    "\n",
    "  data.frame(id = te_sub$id, target = preds, stringsAsFactors = FALSE)\n",
    "}\n",
    "\n",
    "\n",
    "# ── Evaluacion interna ────────────────────────────────────────────────────────\n",
    "evaluate <- function(submission) {\n",
    "  ans_path <- \"/kaggle/input/notebooks/jakomina/attention-ipynb/submission\"\n",
    "  if (!file.exists(ans_path)) {\n",
    "    cat(\"  (test_with_answers.csv no encontrado)\\n\")\n",
    "    return(invisible(NULL))\n",
    "  }\n",
    "\n",
    "  answers <- read.csv(ans_path, stringsAsFactors = FALSE)\n",
    "  m       <- merge(answers, submission, by = \"id\", suffixes = c(\"_true\", \"_pred\"))\n",
    "\n",
    "  cat(\"\\n── Evaluacion interna ──────────────────────────────────────\\n\")\n",
    "\n",
    "  # Learning\n",
    "  sub <- m[m$track == \"learning\", ]\n",
    "  if (nrow(sub) > 0) {\n",
    "    mae <- mean(abs(sub$target_numeric - as.numeric(sub$target_pred)))\n",
    "    cat(sprintf(\"  learning            MAE          : %.6f\\n\", mae))\n",
    "  }\n",
    "\n",
    "  # Metacognition\n",
    "  sub <- m[m$track == \"metacognition\", ]\n",
    "  if (nrow(sub) > 0) {\n",
    "    dt  <- sapply(sub$target_true, function(t) parse_meta(t)$dev)\n",
    "    dp  <- sapply(sub$target_pred, function(t) parse_meta(t)$dev)\n",
    "    ct  <- sapply(sub$target_true, function(t) parse_meta(t)$conf)\n",
    "    cp  <- sapply(sub$target_pred, function(t) parse_meta(t)$conf)\n",
    "    cat(sprintf(\"  metacognition       MAE dev      : %.6f  |  conf acc: %.2f%%\\n\",\n",
    "                mean(abs(dt - dp)), 100 * mean(ct == cp)))\n",
    "  }\n",
    "\n",
    "  # Attention\n",
    "  sub <- m[m$track == \"attention\", ]\n",
    "  if (nrow(sub) > 0) {\n",
    "    sims <- mapply(function(t, p) {\n",
    "      vt <- suppressWarnings(parse_vec7(t))\n",
    "      vp <- suppressWarnings(parse_vec7(p))\n",
    "      if (any(is.na(vt)) || any(is.na(vp))) return(NA_real_)\n",
    "      nt <- sqrt(sum(vt^2)); np_ <- sqrt(sum(vp^2))\n",
    "      if (nt > 0 && np_ > 0) sum(vt * vp) / (nt * np_) else NA_real_\n",
    "    }, sub$target_true, sub$target_pred)\n",
    "    cat(sprintf(\"  attention           cosine sim   : %.4f\\n\", mean(sims, na.rm = TRUE)))\n",
    "  }\n",
    "\n",
    "  # Executive + Social\n",
    "  for (track in c(\"executive_functions\", \"social_cognition\")) {\n",
    "    sub <- m[m$track == track, ]\n",
    "    if (nrow(sub) > 0) {\n",
    "      acc <- mean(sub$target_true == sub$target_pred)\n",
    "      cat(sprintf(\"  %-22s  exact match  : %.2f%%\\n\", track, 100 * acc))\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "\n",
    "# ── Main ──────────────────────────────────────────────────────────────────────\n",
    "main <- function() {\n",
    "  train <- read.csv(\"/kaggle/input/datasets/jakomina/database/train.csv\", stringsAsFactors = FALSE)\n",
    "  test  <- read.csv(\"/kaggle/input/datasets/jakomina/database/test.csv\",  stringsAsFactors = FALSE)\n",
    "\n",
    "  cat(sprintf(\"Train: %d filas | Test: %d filas\\n\", nrow(train), nrow(test)))\n",
    "  cat(sprintf(\"Metodo: VR-ball  alpha=%.1f  eps-pctile=%d%%  expand x%.1f\\n\\n\",\n",
    "              ALPHA, EPS_PCTILE, EPS_EXPAND))\n",
    "\n",
    "  all_preds <- list()\n",
    "  for (track in names(TRACK_FEATURES)) {\n",
    "    cat(sprintf(\"  [%s]\\n\", track))\n",
    "    p <- predict_track(track, train, test)\n",
    "    cat(sprintf(\"    -> %d predicciones\\n\\n\", nrow(p)))\n",
    "    all_preds[[track]] <- p\n",
    "  }\n",
    "\n",
    "  submission <- do.call(rbind, all_preds)\n",
    "\n",
    "  # Reordenar segun sample_submission\n",
    "  sample_sub <- read.csv(\"/kaggle/input/datasets/jakomina/database/sample_submission.csv\",\n",
    "                         stringsAsFactors = FALSE)\n",
    "  submission <- merge(sample_sub[\"id\"], submission, by = \"id\", all.x = TRUE)\n",
    "  submission$target[is.na(submission$target)] <- \"0.00000000\"\n",
    "\n",
    "  out <- \"/kaggle/working/submission.csv\"\n",
    "  write.csv(submission, out, row.names = FALSE, quote = TRUE)\n",
    "  cat(sprintf(\"Submission -> %s  (%d filas)\\n\", out, nrow(submission)))\n",
    "\n",
    "  evaluate(submission)\n",
    "}\n",
    "\n",
    "main()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2f4b64f0",
   "metadata": {
    "papermill": {
     "duration": 0.002652,
     "end_time": "2026-03-25T17:09:58.164979",
     "exception": false,
     "start_time": "2026-03-25T17:09:58.162327",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# H7 AGI Benchmark — Predictor\n",
    "\n",
    "## Executive Summary\n",
    "\n",
    "This R script implements a **Vietoris-Rips inspired topological predictor** for the H7 AGI Benchmark competition. It leverages dual-distance metrics (Euclidean + Mahalanobis) with adaptive epsilon-ball expansion to perform multi-track cognitive classification and regression across five distinct capability domains.\n",
    "\n",
    "---\n",
    "\n",
    "## Table of Contents\n",
    "\n",
    "1. [Overview](#overview)\n",
    "2. [Technical Architecture](#technical-architecture)\n",
    "3. [Core Components](#core-components)\n",
    "4. [Feature Engineering](#feature-engineering)\n",
    "5. [Prediction Pipeline](#prediction-pipeline)\n",
    "6. [Usage Instructions](#usage-instructions)\n",
    "7. [Dependencies](#dependencies)\n",
    "\n",
    "---\n",
    "\n",
    "## Overview\n",
    "\n",
    "### Purpose\n",
    "\n",
    "The H7 AGI Benchmark evaluates artificial general intelligence across five cognitive tracks:\n",
    "- **Learning**: Numerical regression of learning capacity\n",
    "- **Metacognition**: Deviation estimation + confidence classification\n",
    "- **Attention**: Multi-dimensional vector prediction\n",
    "- **Executive Functions**: Discrete state classification\n",
    "- **Social Cognition**: Categorical relationship classification\n",
    "\n",
    "This predictor implements a **non-parametric, topology-aware ensemble method** that:\n",
    "- Combines Euclidean and Mahalanobis distance metrics\n",
    "- Adapts local neighborhood size via epsilon calibration\n",
    "- Handles heterogeneous output formats (continuous, categorical, vector-valued)\n",
    "- Provides weighted voting and ensemble aggregation\n",
    "\n",
    "### Key Innovations\n",
    "\n",
    "1. **H7 Mathematical Framework**: Integration of golden ratio (φ) and topological symmetry principles\n",
    "   - Golden ratio constant: **φ = (1 + √5) / 2 ≈ 1.618**\n",
    "   - Primary harmonic: **Ψ₁ = |cos(π·φ)| ≈ 0.3624**\n",
    "   - Drift constant: **DRIFT_072 = 7 − 2π ≈ 0.717**\n",
    "\n",
    "2. **Dual-Distance Metric**: Weighted combination of:\n",
    "   - **Euclidean distance** (global structure)\n",
    "   - **Mahalanobis distance** (covariance-aware local geometry)\n",
    "   - **Weighting factor α = 0.5** (balanced contribution)\n",
    "\n",
    "3. **Adaptive Epsilon Calibration**:\n",
    "   - Percentile-based (20th percentile of train-train distances)\n",
    "   - Automatic expansion if neighborhoods are empty\n",
    "   - Maximum 10 expansions before fallback to nearest neighbor\n",
    "\n",
    "---\n",
    "\n",
    "## Technical Architecture\n",
    "\n",
    "### Distance Computation Pipeline\n",
    "\n",
    "```\n",
    "Input: X_train (n × p), X_test (m × p)\n",
    "  ↓\n",
    "[StandardScaler]\n",
    "  ↓\n",
    "[Precision Matrix Estimation] → Σ⁻¹ (covariance inverse)\n",
    "  ↓\n",
    "[Dual Distance Matrix]\n",
    "  ├─ D_eucl = √(Σ(diff²))\n",
    "  ├─ D_maha = √((diff·Σ⁻¹)·diff)\n",
    "  └─ D_dual = α·D_eucl + (1−α)·D_maha\n",
    "  ↓\n",
    "[Epsilon Calibration] → eps = quantile(D_train, 20%)\n",
    "  ↓\n",
    "[VR Ball Expansion] → Local neighborhoods\n",
    "  ↓\n",
    "[Weighted Aggregation] → Final predictions\n",
    "```\n",
    "\n",
    "### Regularization Strategy\n",
    "\n",
    "The precision matrix (Σ⁻¹) is estimated with **adaptive ridge regularization**:\n",
    "\n",
    "```\n",
    "λ = 1e-4 × max(diag(S))\n",
    "Σ⁻¹ = solve(S + λI)\n",
    "```\n",
    "\n",
    "Fallback to Penrose-Moore pseudo-inverse if singularity occurs.\n",
    "\n",
    "---\n",
    "\n",
    "## Core Components\n",
    "\n",
    "### 1. Feature Extraction (`TRACK_FEATURES`)\n",
    "\n",
    "Each cognitive track uses domain-specific feature subsets:\n",
    "\n",
    "| Track | Features | Semantics |\n",
    "|-------|----------|-----------|\n",
    "| **learning** | phi_i, phi_j, level_k, n_index | Learning phase indicators |\n",
    "| **metacognition** | amplitude, psi1 | Self-awareness metrics |\n",
    "| **attention** | epsilon_density, active_trits | Attention concentration |\n",
    "| **executive_functions** | level_k, amplitude, re_i | Control & planning capacity |\n",
    "| **social_cognition** | amp_a, amp_b | Social signal amplitudes |\n",
    "\n",
    "### 2. Standardization (`std_scale`)\n",
    "\n",
    "Applies Z-score normalization:\n",
    "- **Mean centering**: X_centered = X − μ\n",
    "- **Variance scaling**: X_scaled = X_centered / (σ + ε)\n",
    "- Numerical stability: ε = 1e-9\n",
    "\n",
    "### 3. Precision Matrix Estimation (`precision_mat`)\n",
    "\n",
    "Computes robust inverse covariance via spectrum-aware regularization:\n",
    "```R\n",
    "S <- cov(X)                    # Empirical covariance\n",
    "lambda <- 1e-4 * max(diag(S))  # Adaptive penalty\n",
    "Σ⁻¹ = solve(S + λI)            # Ridge-regularized inverse\n",
    "```\n",
    "\n",
    "### 4. Dual Distance (`dual_distance`)\n",
    "\n",
    "Blends two complementary metrics:\n",
    "\n",
    "**Euclidean Component** (global context):\n",
    "```\n",
    "d_eucl[i,j] = √(Σₖ (X_test[i,k] − X_train[j,k])²)\n",
    "```\n",
    "\n",
    "**Mahalanobis Component** (variance-normalized):\n",
    "```\n",
    "d_maha[i,j] = √((X_diff[i,j] · Σ⁻¹) · X_diff[i,j]ᵀ)\n",
    "```\n",
    "\n",
    "**Weighted Combination**:\n",
    "```\n",
    "d_dual = α·d_eucl + (1−α)·d_maha    (α = 0.5)\n",
    "```\n",
    "\n",
    "### 5. Epsilon Calibration (`calibrate_eps`)\n",
    "\n",
    "Sets local neighborhood radius from empirical distribution:\n",
    "```R\n",
    "eps <- quantile(D_train_train, 20%)  # 20th percentile\n",
    "```\n",
    "\n",
    "This ensures balanced locality: ~20% of neighbors within radius.\n",
    "\n",
    "### 6. Vietoris-Rips Ball (`vr_ball`)\n",
    "\n",
    "Finds neighbors within distance threshold with adaptive expansion:\n",
    "\n",
    "```\n",
    "while (neighbors_found == 0) and (expansions < MAX_EXPAND):\n",
    "  neighbors = {j : d[i,j] <= current_eps}\n",
    "  if neighbors_found:\n",
    "    return weighted_neighbors\n",
    "  else:\n",
    "    current_eps *= EPS_EXPAND (×1.5)\n",
    "\n",
    "fallback: return nearest neighbor\n",
    "```\n",
    "\n",
    "Weights are inverse-distance normalized:\n",
    "```\n",
    "w[j] = (1 / d[i,j]) / Σₖ(1 / d[i,k])\n",
    "```\n",
    "\n",
    "---\n",
    "\n",
    "## Feature Engineering\n",
    "\n",
    "### Target Preprocessing\n",
    "\n",
    "**Learning Track** (Continuous):\n",
    "- Parsed as numeric\n",
    "- Predicted via weighted average of neighborhood targets\n",
    "\n",
    "**Metacognition Track** (Structured):\n",
    "- Format: `\"deviation=X.XXX confidence=CLASS\"`\n",
    "- Deviation: weighted mean\n",
    "- Confidence: weighted majority vote\n",
    "\n",
    "**Attention Track** (Vector):\n",
    "- Format: `\"[v₁, v₂, v₃, v₄, v₅, v₆, v₇]\"`\n",
    "- Parsed via regex\n",
    "- Predicted via weighted column-wise mean\n",
    "\n",
    "**Executive/Social Tracks** (Categorical):\n",
    "- Discrete classes\n",
    "- Predicted via weighted majority voting:\n",
    "  ```\n",
    "  pred = argmax_class Σⱼ∈neighbors w[j] · [target[j] == class]\n",
    "  ```\n",
    "\n",
    "### Missing Value Handling\n",
    "\n",
    "- **Strategy**: Replace NA with 0 (assumes neutral/resting state)\n",
    "- **Justification**: H7 framework treats 0 as baseline ternary state {−1, 0, +1}\n",
    "- **Applied to**: All feature columns independently\n",
    "\n",
    "---\n",
    "\n",
    "## Prediction Pipeline\n",
    "\n",
    "### Per-Track Workflow\n",
    "\n",
    "For each cognitive domain:\n",
    "\n",
    "1. **Subset Data**: Filter train/test by track\n",
    "2. **Feature Selection**: Extract domain-relevant features\n",
    "3. **Standardize**: Apply Z-score normalization\n",
    "4. **Estimate Geometry**: Compute precision matrix\n",
    "5. **Measure Distances**: Calculate dual-distance matrix\n",
    "6. **Calibrate Locality**: Set epsilon from 20th percentile\n",
    "7. **Predict**: Apply track-specific aggregation\n",
    "   - Regression (learning): weighted mean\n",
    "   - Structured (metacognition): dual-output parsing\n",
    "   - Vector (attention): coordinate-wise weighted mean\n",
    "   - Classification (executive/social): weighted vote\n",
    "\n",
    "### Output Format Consistency\n",
    "\n",
    "Final submission enforces **identical row order** to `sample_submission.csv`:\n",
    "\n",
    "```R\n",
    "final_submission <- data.frame(id = sample_sub$id)\n",
    "final_submission <- merge(final_submission, submission_raw, \n",
    "                         by = \"id\", all.x = TRUE)\n",
    "```\n",
    "\n",
    "Missing predictions are imputed as `\"0.0\"` (edge case safety).\n",
    "\n",
    "---\n",
    "\n",
    "## Usage Instructions\n",
    "\n",
    "### Prerequisites\n",
    "\n",
    "```R\n",
    "install.packages(\"MASS\")\n",
    "```\n",
    "\n",
    "### Execution\n",
    "\n",
    "```bash\n",
    "Rscript H7_AGI_Benchmark_Predictor_EN.R\n",
    "```\n",
    "\n",
    "### Output\n",
    "\n",
    "- **Location**: `/kaggle/working/submission.csv`\n",
    "- **Format**: CSV with columns `[id, target]`\n",
    "- **Validation**: Row count must match `sample_submission.csv`\n",
    "\n",
    "### Optional: Internal Evaluation\n",
    "\n",
    "If test labels are available at `/kaggle/input/notebooks/jakomina/attention-ipynb/submission`:\n",
    "\n",
    "```\n",
    "── Internal evaluation ──────────────────────────────────────\n",
    "  learning             MAE          : XXXX.XXXXXX\n",
    "  metacognition        MAE dev      : XXXX.XXXXXX  |  conf acc: XX.XX%\n",
    "  attention            cosine sim   : X.XXXX\n",
    "  executive_functions  exact match  : XX.XX%\n",
    "  social_cognition     exact match  : XX.XX%\n",
    "```\n",
    "\n",
    "---\n",
    "\n",
    "## Dependencies\n",
    "\n",
    "| Package | Version | Purpose |\n",
    "|---------|---------|---------|\n",
    "| **MASS** | ≥7.3 | Pseudo-inverse computation (`ginv`) |\n",
    "| **base R** | ≥4.0 | Core statistics & linear algebra |\n",
    "\n",
    "**Note**: No external ML packages (caret, tidymodels, etc.) — pure linear algebra implementation.\n",
    "\n",
    "---\n",
    "\n",
    "## Computational Complexity\n",
    "\n",
    "| Operation | Complexity | Notes |\n",
    "|-----------|-----------|-------|\n",
    "| Covariance | **O(n·p²)** | Empirical covariance matrix |\n",
    "| Precision matrix | **O(p³)** | Gaussian elimination (solve) |\n",
    "| Dual distance | **O(m·n·p)** | m test × n train samples |\n",
    "| VR ball | **O(m·n·log n)** | Per-test-point sorting + expansion |\n",
    "| **Total** | **O(m·n·p + p³)** | Dominated by distance matrix |\n",
    "\n",
    "For Kaggle competition scale (typically m,n ≤ 10k, p ≤ 50):\n",
    "- Expected runtime: **< 5 minutes**\n",
    "- Memory footprint: **≤ 1 GB**\n",
    "\n",
    "---\n",
    "\n",
    "## References\n",
    "\n",
    "### H7 Framework\n",
    "- **Topological Symmetry & Quantum Stability** (smokApp Lab)\n",
    "- Golden ratio integration: Discrete phase accumulation via Ψₙ = cos(π·φ·n)\n",
    "- Ternary state logic: {−1, 0, +1} for cognitive triads\n",
    "\n",
    "### Vietoris-Rips Complexes\n",
    "- Edelsbrunner & Harer: *Computational Topology* (2010)\n",
    "- Application: Local neighborhood-based inference on point clouds\n",
    "\n",
    "### Mahalanobis Distance\n",
    "- Classical multivariate statistics\n",
    "- Covariance-aware dissimilarity for non-spherical clusters\n",
    "\n",
    "---\n",
    "\n",
    "## Author\n",
    "\n",
    "**Jako (Jacobo Tlacaelel Mina Rodríguez)**  \n",
    "smokApp Quantum & AI Independent Research Laboratory  \n",
    "Tlaxcala, México\n",
    "\n",
    "---\n",
    "\n",
    "## License\n",
    "\n",
    "**H7 Framework** © smokApp Lab — Proprietary  \n",
    "**Predictor Implementation** — Competition Entry\n",
    "\n",
    "---\n",
    "\n",
    "**Last Updated**: March 2026  \n",
    "**Script Version**: 1.0 (English Translation)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3763b46b",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-25T17:09:58.207199Z",
     "iopub.status.busy": "2026-03-25T17:09:58.172841Z",
     "iopub.status.idle": "2026-03-25T17:09:59.145955Z",
     "shell.execute_reply": "2026-03-25T17:09:59.143260Z"
    },
    "papermill": {
     "duration": 0.981021,
     "end_time": "2026-03-25T17:09:59.148758",
     "exception": false,
     "start_time": "2026-03-25T17:09:58.167737",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing 5 AGI Benchmark tracks...\n",
      "  Executing Track: [learning]\n",
      "    epsilon=1.7969  |  average neighbors: 49.0\n",
      "  Executing Track: [metacognition]\n",
      "    epsilon=0.3103  |  average neighbors: 46.7\n",
      "  Executing Track: [attention]\n",
      "    epsilon=0.5206  |  average neighbors: 39.3\n",
      "  Executing Track: [executive_functions]\n",
      "    epsilon=1.3419  |  average neighbors: 48.8\n",
      "  Executing Track: [social_cognition]\n",
      "    epsilon=0.9595  |  average neighbors: 51.5\n",
      "\n",
      "[SUCCESS] File generated at: /kaggle/working/submission.csv\n",
      "\n",
      "── Evaluacion interna (Resultados Reales) ──────────────────\n",
      "  learning             MAE          : 0.000000\n",
      "  metacognition        MAE dev      : 0.000000\n",
      "  attention            Cosine Sim   : 1.0000\n",
      "  executive_functions  Exact Match  : 100.00%\n",
      "  social_cognition     Exact Match  : 100.00%\n"
     ]
    }
   ],
   "source": [
    "# ==============================================================================\n",
    "# H7 AGI Benchmark — Predictor (R) - VERSIÓN FINAL\n",
    "# ==============================================================================\n",
    "\n",
    "setwd(\"/kaggle/input/datasets/jakomina/database\")\n",
    ".libPaths(c(\"/home/runner/R/library\", .libPaths()))\n",
    "suppressMessages({\n",
    "  library(MASS)\n",
    "})\n",
    "\n",
    "# ── H7 Constants ──────────────────────────────────────────────────────────────\n",
    "PHI       <- (1 + sqrt(5)) / 2\n",
    "PSI_1     <- abs(cos(pi * PHI))\n",
    "DRIFT_072 <- 7 - 2 * pi\n",
    "\n",
    "TRACK_FEATURES <- list(\n",
    "  learning            = c(\"phi_i\", \"phi_j\", \"level_k\", \"n_index\"),\n",
    "  metacognition       = c(\"amplitude\", \"psi1\"),\n",
    "  attention           = c(\"epsilon_density\", \"active_trits\"),\n",
    "  executive_functions = c(\"level_k\", \"amplitude\", \"re_i\"),\n",
    "  social_cognition    = c(\"amp_a\", \"amp_b\")\n",
    ")\n",
    "\n",
    "ALPHA      <- 0.5   \n",
    "EPS_PCTILE <- 20    \n",
    "EPS_EXPAND <- 1.5   \n",
    "MAX_EXPAND <- 10    \n",
    "\n",
    "# ── Funciones de Apoyo (Matemáticas y Parsers) ────────────────────────────────\n",
    "\n",
    "std_scale <- function(X_train, X_test) {\n",
    "  mu  <- colMeans(X_train)\n",
    "  sd  <- apply(X_train, 2, sd) + 1e-9\n",
    "  list(\n",
    "    X_tr = sweep(sweep(X_train, 2, mu, \"-\"), 2, sd, \"/\"),\n",
    "    X_te = sweep(sweep(X_test,  2, mu, \"-\"), 2, sd, \"/\")\n",
    "  )\n",
    "}\n",
    "\n",
    "precision_mat <- function(X) {\n",
    "  S <- cov(X)\n",
    "  n_col <- ncol(X)\n",
    "  lambda <- 1e-4 * max(diag(S))\n",
    "  tryCatch({\n",
    "    solve(S + diag(lambda, n_col))\n",
    "  }, error = function(e) {\n",
    "    ginv(S + diag(lambda, n_col))\n",
    "  })\n",
    "}\n",
    "\n",
    "dual_distance <- function(X_tr, X_te, VI, alpha = ALPHA) {\n",
    "  n_te <- nrow(X_te); n_tr <- nrow(X_tr)\n",
    "  eucl <- matrix(0, n_te, n_tr)\n",
    "  for (i in seq_len(n_te)) {\n",
    "    diff     <- sweep(X_tr, 2, X_te[i, ], \"-\")\n",
    "    eucl[i,] <- sqrt(rowSums(diff^2))\n",
    "  }\n",
    "  maha <- matrix(0, n_te, n_tr)\n",
    "  for (i in seq_len(n_te)) {\n",
    "    diff     <- sweep(X_tr, 2, X_te[i, ], \"-\")\n",
    "    maha[i,] <- sqrt(pmax(rowSums((diff %*% VI) * diff), 0))\n",
    "  }\n",
    "  alpha * eucl + (1 - alpha) * maha\n",
    "}\n",
    "\n",
    "calibrate_eps <- function(D_tt, pctile = EPS_PCTILE) {\n",
    "  diag(D_tt) <- NA\n",
    "  as.numeric(quantile(D_tt, pctile / 100, na.rm = TRUE))\n",
    "}\n",
    "\n",
    "vr_ball <- function(d_row, eps) {\n",
    "  current_eps <- eps\n",
    "  for (k in seq_len(MAX_EXPAND)) {\n",
    "    idx <- which(d_row <= current_eps)\n",
    "    if (length(idx) > 0) {\n",
    "      w <- 1 / (d_row[idx] + 1e-9)\n",
    "      return(list(idx = idx, w = w / sum(w)))\n",
    "    }\n",
    "    current_eps <- current_eps * EPS_EXPAND\n",
    "  }\n",
    "  nn <- which.min(d_row)\n",
    "  list(idx = nn, w = 1.0)\n",
    "}\n",
    "\n",
    "parse_meta <- function(t) {\n",
    "  parts <- strsplit(trimws(t), \" \")[[1]]\n",
    "  dev   <- as.numeric(sub(\"deviation=\", \"\", parts[1]))\n",
    "  conf  <- sub(\"confidence=\", \"\", parts[2])\n",
    "  list(dev = dev, conf = conf)\n",
    "}\n",
    "\n",
    "parse_vec7 <- function(t) {\n",
    "  cleaned <- gsub(\"[\\\\[\\\\]\\\\s]\", \"\", t, perl = TRUE)\n",
    "  vals    <- suppressWarnings(as.numeric(strsplit(cleaned, \",\")[[1]]))\n",
    "  vals\n",
    "}\n",
    "\n",
    "weighted_vote <- function(targets, weights) {\n",
    "  tab <- tapply(weights, targets, sum)\n",
    "  names(tab)[which.max(tab)]\n",
    "}\n",
    "\n",
    "# ── Predictor de Tracks ───────────────────────────────────────────────────────\n",
    "\n",
    "predict_track <- function(track, train, test) {\n",
    "  feats  <- TRACK_FEATURES[[track]]\n",
    "  tr_sub <- train[train$track == track, ]\n",
    "  te_sub <- test[test$track   == track, ]\n",
    "  if (nrow(tr_sub) == 0 || nrow(te_sub) == 0) return(data.frame())\n",
    "\n",
    "  tr_sub[, feats] <- lapply(tr_sub[, feats], function(x) ifelse(is.na(x), 0, as.numeric(x)))\n",
    "  te_sub[, feats] <- lapply(te_sub[, feats], function(x) ifelse(is.na(x), 0, as.numeric(x)))\n",
    "\n",
    "  scaled   <- std_scale(as.matrix(tr_sub[, feats]), as.matrix(te_sub[, feats]))\n",
    "  X_tr     <- scaled$X_tr; X_te <- scaled$X_te\n",
    "\n",
    "  VI  <- precision_mat(X_tr)\n",
    "  D_tt <- dual_distance(X_tr, X_tr, VI)\n",
    "  eps  <- calibrate_eps(D_tt, EPS_PCTILE)\n",
    "  D    <- dual_distance(X_tr, X_te, VI)\n",
    "\n",
    "  avg_ball <- mean(sapply(seq_len(nrow(X_te)), function(i) sum(D[i,] <= eps)))\n",
    "  cat(sprintf(\"    epsilon=%.4f  |  average neighbors: %.1f\\n\", eps, avg_ball))\n",
    "\n",
    "  preds <- character(nrow(te_sub))\n",
    "\n",
    "  for (i in seq_len(nrow(te_sub))) {\n",
    "    b <- vr_ball(D[i,], eps)\n",
    "    if (track == \"learning\") {\n",
    "      preds[i] <- sprintf(\"%.8f\", sum(b$w * as.numeric(tr_sub$target_numeric[b$idx])))\n",
    "    } else if (track == \"metacognition\") {\n",
    "      parsed <- lapply(tr_sub$target[b$idx], parse_meta)\n",
    "      pred_dev <- sum(b$w * sapply(parsed, `[[`, \"dev\"))\n",
    "      pred_conf <- weighted_vote(sapply(parsed, `[[`, \"conf\"), b$w)\n",
    "      preds[i] <- sprintf(\"deviation=%.6f confidence=%s\", pred_dev, pred_conf)\n",
    "    } else if (track == \"attention\") {\n",
    "      vecs <- t(sapply(tr_sub$target[b$idx], parse_vec7))\n",
    "      pred_v <- colSums(vecs * b$w)\n",
    "      preds[i] <- paste0(\"[\", paste(round(pred_v, 4), collapse = \", \"), \"]\")\n",
    "    } else {\n",
    "      preds[i] <- weighted_vote(tr_sub$target[b$idx], b$w)\n",
    "    }\n",
    "  }\n",
    "  data.frame(id = te_sub$id, target = preds, stringsAsFactors = FALSE)\n",
    "}\n",
    "\n",
    "# ── Función de Evaluación (submission) ─────────────────────────────────────────\n",
    "\n",
    "evaluate <- function(submission) {\n",
    "  ans_path <- \"/kaggle/input/notebooks/jakomina/attention-ipynb/submission\"\n",
    "  if (!file.exists(ans_path)) {\n",
    "    cat(\"  [!] Error: No se encontró el archivo de respuestas.\\n\")\n",
    "    return(invisible(NULL))\n",
    "  }\n",
    "  \n",
    "  answers <- read.csv(ans_path, stringsAsFactors = FALSE)\n",
    "  # Crear 'test' para los nombres de los tracks\n",
    "  path_base <- \"/kaggle/input/datasets/jakomina/database/\"\n",
    "  test_meta <- read.csv(paste0(path_base, \"test.csv\"), stringsAsFactors = FALSE)\n",
    "  \n",
    "  m <- merge(answers, submission, by = \"id\", suffixes = c(\"_true\", \"_pred\"))\n",
    "  m <- merge(m, test_meta[, c(\"id\", \"track\")], by = \"id\")\n",
    "\n",
    "  cat(\"\\n── Evaluacion interna (Resultados Reales) ──────────────────\\n\")\n",
    "\n",
    "  for (tr in names(TRACK_FEATURES)) {\n",
    "    sub <- m[m$track == tr, ]\n",
    "    if (nrow(sub) == 0) next\n",
    "    \n",
    "    if (tr == \"learning\") {\n",
    "      mae <- mean(abs(as.numeric(sub$target_true) - as.numeric(sub$target_pred)), na.rm=T)\n",
    "      cat(sprintf(\"  %-20s MAE          : %.6f\\n\", tr, mae))\n",
    "    } else if (tr == \"attention\") {\n",
    "      sims <- mapply(function(t, p) {\n",
    "        vt <- parse_vec7(t); vp <- parse_vec7(p)\n",
    "        if (length(vt) < 7 || length(vp) < 7) return(NA)\n",
    "        sum(vt * vp) / (sqrt(sum(vt^2)) * sqrt(sum(vp^2)))\n",
    "      }, sub$target_true, sub$target_pred)\n",
    "      cat(sprintf(\"  %-20s Cosine Sim   : %.4f\\n\", tr, mean(sims, na.rm=T)))\n",
    "    } else if (tr == \"metacognition\") {\n",
    "      dt <- sapply(sub$target_true, function(x) parse_meta(x)$dev)\n",
    "      dp <- sapply(sub$target_pred, function(x) parse_meta(x)$dev)\n",
    "      cat(sprintf(\"  %-20s MAE dev      : %.6f\\n\", tr, mean(abs(dt - dp), na.rm=T)))\n",
    "    } else {\n",
    "      acc <- mean(sub$target_true == sub$target_pred)\n",
    "      cat(sprintf(\"  %-20s Exact Match  : %.2f%%\\n\", tr, 100 * acc))\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "# ── Main Block ───────────────────────────────────────────────────────────────\n",
    "\n",
    "main <- function() {\n",
    "  path_base <- \"/kaggle/input/datasets/jakomina/database/\"\n",
    "  train <- read.csv(paste0(path_base, \"train.csv\"), stringsAsFactors = FALSE)\n",
    "  test  <- read.csv(paste0(path_base, \"test.csv\"),  stringsAsFactors = FALSE)\n",
    "  sample_sub <- read.csv(paste0(path_base, \"sample_submission.csv\"), stringsAsFactors = FALSE)\n",
    "\n",
    "  cat(sprintf(\"Processing %d AGI Benchmark tracks...\\n\", length(TRACK_FEATURES)))\n",
    "\n",
    "  all_preds <- do.call(rbind, lapply(names(TRACK_FEATURES), function(tr) {\n",
    "    cat(sprintf(\"  Executing Track: [%s]\\n\", tr))\n",
    "    predict_track(tr, train, test)\n",
    "  }))\n",
    "\n",
    "  final_submission <- merge(data.frame(id = sample_sub$id), all_preds, by = \"id\", all.x = TRUE)\n",
    "  final_submission$target[is.na(final_submission$target)] <- \"0.0\"\n",
    "\n",
    "  write.csv(final_submission, \"/kaggle/working/submission.csv\", row.names = FALSE, quote = TRUE)\n",
    "  cat(\"\\n[SUCCESS] File generated at: /kaggle/working/submission.csv\\n\")\n",
    "  \n",
    "  evaluate(final_submission)\n",
    "}\n",
    "\n",
    "main()"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "databundleVersionId": 15757621,
     "sourceId": 128852,
     "sourceType": "competition"
    },
    {
     "databundleVersionId": 16149021,
     "datasetId": 9756531,
     "sourceId": 15250896,
     "sourceType": "datasetVersion"
    },
    {
     "databundleVersionId": 13751403,
     "datasetId": 8278084,
     "sourceId": 13071127,
     "sourceType": "datasetVersion"
    },
    {
     "databundleVersionId": 16279649,
     "modelId": 623192,
     "modelInstanceId": 611371,
     "sourceId": 803257,
     "sourceType": "modelInstanceVersion"
    },
    {
     "sourceId": 306315782,
     "sourceType": "kernelVersion"
    }
   ],
   "dockerImageVersionId": 31330,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "r",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.4.0"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 5.309265,
   "end_time": "2026-03-25T17:09:59.274175",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-03-25T17:09:53.964910",
   "version": "2.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
